### ISSUE TITLE
GET /api/dashboard/home/info  Not Found for PE 3.2.2

### ISSUE THREAD

**Issue by abdalmoti** [thingsboard/dart_thingsboard_pe_client#1]
Error : GET /api/dashboard/home/info for Version PE 3.2.2  not found 'message: "Http status error [404]'

**Comment by vvlladd28** [comment]
Hi @abdalmoti,
Yes, this API is not available in TB PE 3.2.2.
This endpoint will be added to the new release TB 3.3.0.

**Comment by abdalmoti** [comment]
When TB PE 3.3.0 will be available to upgrade?

**Comment by vvlladd28** [comment]
Release is scheduled for 2-3 weeks

**Comment by vvlladd28** [comment]
Hi @abdalmoti,
The release took place on August 13.
